name: Commit Message Validation

on:
  push:
    branches:
      - feature/*
      - hotfix/*

jobs:
  validate:
    name: Validate Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install pnpm
        run: |
          npm i -g pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Validate commit messages
        run: |
          pnpm commitlint --last --verbose
